name: unique_identifier
description: A new Flutter plugin for fetching the unique identifier from android and ios.
version: 0.1.0
author: Karan Tanwar <karantanwar.nitd@gmail.com>
homepage: https://github.com/karantanwar/unique_identifier

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: altercode.xyz.uniqueidentifier
    pluginClass: UniqueIdentifierPlugin
